import type { Locale } from '../../../lib/i18n'

const uz = {
  games: "O'yinlar", back: 'Orqaga', start: 'Boshlash', ready: 'Tayyorman', next: 'Keyingi', stop: 'Yakunlash',
  retry: 'Qayta urinish', again: "Yana o'ynash", resume: 'Davom ettirish', finish: "O'yinni yakunlash",
  character: 'Hamrohingizni tanlang', level: 'Daraja', theme: 'Mavzu', rounds: 'Raund', score: 'Ball',
  best: 'Shaxsiy rekord', weekly: 'Haftalik reyting', history: 'Oxirgi natijalar', achievements: 'Yutuqlar',
  empty: "Hozircha natijalar yo'q. Birinchi bo'lib o'ynang!", loading: 'Yuklanmoqda...', saving: 'Tekshirilmoqda...',
  saved: 'Natija saqlandi', completed: 'Ajoyib mashg‘ulot!', review: 'Natijalarni ko‘rib chiqing',
  seconds: 'soniya', answer: 'Javobingiz', correct: "To'g'ri variant", explanation: 'Izoh', heard: 'Aytilgan so‘zlar',
  listen: 'Eshitish', listening: 'Sizni eshityapman. Ruscha gapiring.', preparing: 'Mikrofon ulanmoqda...',
  speak: 'Gapirish', submit: 'Javobni yuborish', type: 'Yozib javob berish', voice: 'Ovoz bilan javob berish',
  textMode: 'Yozma mashq: javobingizni rus tilida kiriting.', unsupported: 'Bu brauzer ovozni matnga aylantirishni qo‘llamaydi. Chrome yoki Safari orqali kiring yoki yozma mashqni tanlang.',
  micDenied: 'Mikrofonga ruxsat bering', micHelp: 'Manzil yonidagi sayt sozlamalari → Ruxsatlar → Mikrofon → Ruxsat berish. Keyin qayta urinib ko‘ring.',
  micFailed: 'Ovoz aniqlanmadi. Mikrofon va internetni tekshirib, qayta urinib ko‘ring.',
  error: 'So‘rov bajarilmadi. Internetni tekshiring va qayta urinib ko‘ring. Natijangiz yuborilmaguncha keyingi savolga o‘tilmaydi.',
  locked: 'Bu o‘yin hali ochilmagan.', unlock: 'Avval kerakli darslarni tugating.', disabled: 'Bu o‘yin administrator tomonidan hali yoqilmagan.',
  rules: 'Qanday o‘ynaladi?', practice: 'Ruscha gapiring. Har bir javob uchun aniq tahlilni ko‘ring.',
  silence: 'Vaqt ketyapti. Esingizdagi ruscha so‘zlarni ayting!',
  endConfirm: 'Hozir yakunlaysizmi? Qolgan savollar javobsiz qoladi.',
  map: 'Shahar xaritasi', clues: 'Dalillar daftari', noClues: 'Qahramonlarga savol bering. Topilgan dalillar shu yerda saqlanadi.',
  questions: 'Savollar', enter: 'Kirish', accuse: 'Aybdorni aytish', accusation: 'Kim aybdor va nima uchun? Ruscha 1–2 gap bilan tushuntiring.',
  question: 'Ish haqida ruscha savol bering.', investigated: 'So‘roq qilindi', solved: 'Ish ochildi!', unsolved: 'Dalillarni yana ko‘rib chiqing',
  city: 'Sizning o‘yin shaharingiz', daily: 'Bugungi topshiriqlar', progress: 'Natijalar va yutuqlar',
  detective: 'Detektiv idorasi', total: 'Jami ball', leaderboard: 'Reyting', allTime: 'Barcha vaqt',
  leave: 'Xaritaga qaytish', record: 'Yangi rekord!', timeUp: 'Vaqt tugadi', noAnswer: 'Javob berilmadi',
  speed: 'Tezlik', relevance: 'Mavzuga moslik', grammar: 'Grammatika', emotion: 'Hissiyot', bonus: 'Bonus',
  unique: 'Yangi so‘z', repeat: 'Takror', offTopic: 'Mavzudan tashqari', lessonBonus: 'Darsdan tanish so‘z',
  penguin: 'Pingvin', panda: 'Panda', feather: 'Pero', bear: 'Ayiq novvoy', fox: 'Tulki pochtachi',
  chooseTopic: 'Istalgan mavzuni tanlang', savedGame: 'Tugallanmagan o‘yin bor', audioFailed: 'Ovozni ijro qilib bo‘lmadi. Matnni o‘qib davom etishingiz mumkin.',
  roleplay: 'Qahramon kabi javob berish', normal: 'O‘z nomimdan', rank: 'O‘rin', player: 'Ishtirokchi',
  fresh: 'Yangi o‘yin', microphone: 'Mikrofon', timeNote: 'Taymer mikrofon tayyor bo‘lgandan keyin boshlanadi.',
}
type Copy = { [K in keyof typeof uz]: string }
const ru: Copy = {
  games: 'Игры', back: 'Назад', start: 'Начать', ready: 'Я готов', next: 'Дальше', stop: 'Закончить',
  retry: 'Повторить', again: 'Играть ещё', resume: 'Продолжить', finish: 'Завершить игру',
  character: 'Выберите напарника', level: 'Уровень', theme: 'Тема', rounds: 'Раунд', score: 'Баллы',
  best: 'Личный рекорд', weekly: 'Рейтинг за неделю', history: 'Последние результаты', achievements: 'Достижения',
  empty: 'Результатов пока нет. Сыграйте первым!', loading: 'Загрузка...', saving: 'Проверяем ответ...',
  saved: 'Результат сохранён', completed: 'Отличная практика!', review: 'Посмотрите результаты',
  seconds: 'секунд', answer: 'Ваш ответ', correct: 'Правильный вариант', explanation: 'Объяснение', heard: 'Распознанные слова',
  listen: 'Послушать', listening: 'Слушаю вас. Говорите по-русски.', preparing: 'Подключаем микрофон...',
  speak: 'Говорить', submit: 'Отправить ответ', type: 'Ответить текстом', voice: 'Ответить голосом',
  textMode: 'Письменная практика: введите ответ по-русски.', unsupported: 'Этот браузер не поддерживает распознавание речи. Откройте Chrome или Safari либо выберите письменную практику.',
  micDenied: 'Разрешите доступ к микрофону', micHelp: 'Настройки сайта рядом с адресом → Разрешения → Микрофон → Разрешить. Затем попробуйте снова.',
  micFailed: 'Не удалось распознать речь. Проверьте микрофон и интернет, затем попробуйте снова.',
  error: 'Запрос не выполнен. Проверьте интернет и повторите. Следующий вопрос не откроется, пока ответ не отправлен.',
  locked: 'Игра пока недоступна.', unlock: 'Сначала завершите нужные уроки.', disabled: 'Администратор ещё не включил эту игру.',
  rules: 'Как играть?', practice: 'Говорите по-русски и получайте разбор каждого ответа.',
  silence: 'Время идёт. Говорите любые слова по теме!',
  endConfirm: 'Завершить сейчас? Оставшиеся вопросы останутся без ответа.',
  map: 'Карта города', clues: 'Журнал улик', noClues: 'Задавайте вопросы персонажам. Найденные улики появятся здесь.',
  questions: 'Вопросы', enter: 'Войти', accuse: 'Назвать виновного', accusation: 'Кто виноват и почему? Объясните по-русски в 1–2 предложениях.',
  question: 'Задайте вопрос по делу на русском.', investigated: 'Допрошен', solved: 'Дело раскрыто!', unsolved: 'Посмотрите на улики ещё раз',
  city: 'Ваш игровой город', daily: 'Задания на сегодня', progress: 'Результаты и достижения',
  detective: 'Детективное агентство', total: 'Всего баллов', leaderboard: 'Рейтинг', allTime: 'За всё время',
  leave: 'Вернуться на карту', record: 'Новый рекорд!', timeUp: 'Время вышло', noAnswer: 'Нет ответа',
  speed: 'Скорость', relevance: 'По теме', grammar: 'Грамматика', emotion: 'Эмоции', bonus: 'Бонус',
  unique: 'Новое слово', repeat: 'Повтор', offTopic: 'Не по теме', lessonBonus: 'Слово из урока',
  penguin: 'Пингвин', panda: 'Панда', feather: 'Перо', bear: 'Медведь-пекарь', fox: 'Лиса-почтальон',
  chooseTopic: 'Выберите любую тему', savedGame: 'У вас есть незавершённая игра', audioFailed: 'Не удалось воспроизвести звук. Можно прочитать текст и продолжить.',
  roleplay: 'Ответить в роли персонажа', normal: 'От своего имени', rank: 'Место', player: 'Игрок',
  fresh: 'Новая игра', microphone: 'Микрофон', timeNote: 'Таймер начнётся, когда микрофон будет готов.',
}
const en: Copy = {
  games: 'Games', back: 'Back', start: 'Start', ready: 'Ready', next: 'Next', stop: 'Finish',
  retry: 'Try again', again: 'Play again', resume: 'Resume', finish: 'Finish game',
  character: 'Choose your companion', level: 'Level', theme: 'Topic', rounds: 'Round', score: 'Score',
  best: 'Personal best', weekly: 'Weekly leaderboard', history: 'Recent results', achievements: 'Achievements',
  empty: 'No results yet. Be the first to play!', loading: 'Loading...', saving: 'Checking your answer...',
  saved: 'Result saved', completed: 'Great practice!', review: 'Review your results',
  seconds: 'seconds', answer: 'Your answer', correct: 'Correct version', explanation: 'Explanation', heard: 'Recognised words',
  listen: 'Listen', listening: 'Listening. Speak in Russian.', preparing: 'Connecting microphone...',
  speak: 'Speak', submit: 'Submit answer', type: 'Type an answer', voice: 'Answer by voice',
  textMode: 'Written practice: enter your answer in Russian.', unsupported: 'Speech recognition is unavailable in this browser. Use Chrome or Safari, or choose written practice.',
  micDenied: 'Allow microphone access', micHelp: 'Site settings next to the address → Permissions → Microphone → Allow. Then try again.',
  micFailed: 'Could not recognise speech. Check your microphone and connection, then try again.',
  error: 'Request failed. Check your connection and retry. Your next question stays closed until this answer is submitted.',
  locked: 'This game is not unlocked yet.', unlock: 'Complete the required lessons first.', disabled: 'The administrator has not enabled this game yet.',
  rules: 'How to play', practice: 'Speak Russian and see a breakdown of every answer.',
  silence: 'Time is running. Say any words you know on this topic!',
  endConfirm: 'Finish now? The remaining questions will be unanswered.',
  map: 'City map', clues: 'Evidence journal', noClues: 'Question the characters. Discovered clues will appear here.',
  questions: 'Questions', enter: 'Enter', accuse: 'Name the culprit', accusation: 'Who is guilty, and why? Explain in 1–2 Russian sentences.',
  question: 'Ask a question about the case in Russian.', investigated: 'Questioned', solved: 'Case solved!', unsolved: 'Take another look at the evidence',
  city: 'Your game city', daily: 'Daily challenges', progress: 'Results and achievements',
  detective: 'Detective agency', total: 'Total points', leaderboard: 'Leaderboard', allTime: 'All time',
  leave: 'Back to map', record: 'New personal best!', timeUp: 'Time is up', noAnswer: 'No answer',
  speed: 'Speed', relevance: 'Relevance', grammar: 'Grammar', emotion: 'Emotion', bonus: 'Bonus',
  unique: 'New word', repeat: 'Repeated', offTopic: 'Off topic', lessonBonus: 'Word from a lesson',
  penguin: 'Penguin', panda: 'Panda', feather: 'Feather', bear: 'Bear the baker', fox: 'Fox the postman',
  chooseTopic: 'Choose any topic', savedGame: 'You have an unfinished game', audioFailed: 'Audio playback failed. You can read the text and continue.',
  roleplay: 'React as your character', normal: 'As myself', rank: 'Rank', player: 'Player',
  fresh: 'New game', microphone: 'Microphone', timeNote: 'The timer starts only when your microphone is ready.',
}

export const copies: Record<Locale, Copy> = { uz, ru, en }
export type GameCopy = Copy
export const gameSlugs = ['tez-gapir', 'error-hunt', 'first-reaction', 'ice-mystery'] as const
export type GameSlug = typeof gameSlugs[number]
export const gameLabels: Record<GameSlug, Record<Locale, { title: string; description: string; rules: string }>> = {
  'tez-gapir': {
    uz: { title: 'Tez gapir', description: '30 soniya. Bitta mavzu. Nechta ruscha so‘z bilasiz?', rules: 'Mavzuga mos yangi so‘z: +1. Takror va mavzudan tashqari so‘z: −1. To‘g‘ri to‘liq gap: +2. Bir mashg‘ulotda 3–5 raund.' },
    ru: { title: 'Говори быстро', description: '30 секунд. Одна тема. Сколько слов вы вспомните?', rules: 'Новое слово по теме: +1. Повтор или слово не по теме: −1. Правильное полное предложение: +2. От 3 до 5 раундов.' },
    en: { title: 'Speak fast', description: '30 seconds. One topic. How many Russian words do you know?', rules: 'New relevant word: +1. Repeated or off-topic word: −1. A correct full sentence: +2. Play 3–5 rounds.' },
  },
  'error-hunt': {
    uz: { title: 'Xato ovchisi', description: 'Xatoni ko‘ring va to‘g‘ri variantni ovoz chiqarib ayting.', rules: 'Har bir gapga 10 soniya. To‘g‘ri javob: +5; 3 soniyada: +7. Xatoni takrorlash: −2. Ayrim gaplarda xato yo‘q!' },
    ru: { title: 'Ловец ошибок', description: 'Найдите ошибку и произнесите правильный вариант.', rules: '10 секунд на предложение. Верное исправление: +5; за 3 секунды: +7. Повтор ошибки: −2. В некоторых предложениях ошибки нет!' },
    en: { title: 'Error hunter', description: 'Spot the mistake and say the corrected sentence aloud.', rules: '10 seconds per sentence. Correct: +5; within 3 seconds: +7. Repeating the mistake: −2. Some sentences are already correct!' },
  },
  'first-reaction': {
    uz: { title: 'Birinchi reaksiya', description: 'Kutilmagan vaziyat. Ruscha javob uchun 5 soniya.', rules: '7 ta vaziyat. Tezlik: +3, moslik: +2, grammatika: +2, hissiy ifoda: +1. Jim qolish: −1. Mavzudan tashqari: −2.' },
    ru: { title: 'Первая реакция', description: 'Неожиданная ситуация. 5 секунд на реакцию.', rules: '7 ситуаций. Скорость: +3, по теме: +2, грамматика: +2, эмоция: +1. Молчание: −1. Не по теме: −2.' },
    en: { title: 'First reaction', description: 'An unexpected situation. 5 seconds to react in Russian.', rules: '7 situations. Speed: +3, relevance: +2, grammar: +2, expression: +1. Silence: −1. Off topic: −2.' },
  },
  'ice-mystery': {
    uz: { title: 'Muzli shahar siri', description: '5 ta joy. 5 ta dalil. Baliqni kim o‘g‘irlagan?', rules: 'Ruscha savollar bering. Har bir qahramonga 10 tagacha savol. Dalillarni to‘plab, aybdorni va sababini ovoz bilan ayting. Ishni keyin davom ettirish mumkin.' },
    ru: { title: 'Тайна ледяного города', description: '5 локаций. 5 улик. Кто украл рыбу?', rules: 'Задавайте вопросы по-русски: до 10 каждому персонажу. Соберите улики, назовите виновного и объясните почему. Расследование можно продолжить позже.' },
    en: { title: 'Mystery of the ice city', description: '5 locations. 5 clues. Who stole the fish?', rules: 'Ask questions in Russian, up to 10 per character. Gather evidence, name the culprit and explain why aloud. You can resume the case later.' },
  },
}

export const isSpeakingGame = (slug: string): slug is GameSlug => gameSlugs.includes(slug as GameSlug)
